# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      - name: Install dependencies
        run: |
          python build-system-script.py install-depends
      - name: Run tests
        run: |
          python build-system-script.py test
      - name: Check coverage
        run: |
          python build-system-script.py check-coverage
      - name: Lint with flake8
        run: |
          python build-system-script.py flake8
      - name: Lint with Pylint
        run: |
          python build-system-script.py pylint
